name: Check
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
on:
  pull_request:
    # On any pull requests to $default-branch
    branches: ['main']
jobs:
  terraform:
    name: "Terraform"
    uses: KomalkN/terraform-make-workfile/.github/workflows/terraform-check.yaml@main
    secrets:
      GH_INFRA_PAT: ${{ secrets.GH_INFRA_PAT }}
      role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
